# Generated by Django 3.1.7 on 2021-03-13 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asamblea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(default='Ingrese un breve descripcion', max_length=300)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60)),
                ('direccion_calle', models.CharField(max_length=20)),
                ('direccion_numero', models.IntegerField()),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre', 'telefono', 'fecha_modificacion', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
            ],
            options={
                'ordering': ['nombre', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Seleccione un estado civil', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(help_text='Seleccione un genero', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='Ingrese un breve descripcion')),
            ],
            options={
                'ordering': ['nombre', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre', 'fecha_creacion', 'fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('password', models.CharField(default='1234', max_length=50)),
            ],
            options={
                'ordering': ['username', 'email', 'nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaAsamblea',
            fields=[
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(default='Ingrese un breve descripcion', max_length=300)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('asamblea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion.asamblea')),
            ],
            options={
                'ordering': ['titulo', 'fecha_creacion', 'fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='SeccionIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=2000)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('id_fk_tema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.tema')),
                ('id_fk_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario')),
            ],
            options={
                'ordering': ['titulo', 'texto', 'fecha_modificacion', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('id_fk_distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.distrito')),
            ],
            options={
                'ordering': ['nombre', 'region'],
            },
        ),
        migrations.AddField(
            model_name='asamblea',
            name='id_fk_comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.comuna'),
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField(default='Ingrese um texto', max_length=2000)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('id_fk_tema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.tema')),
                ('id_fk_propuesta_asamblea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.propuestaasamblea')),
            ],
            options={
                'ordering': ['titulo', 'fecha_creacion', 'fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('rut', models.CharField(max_length=10)),
                ('resumen', models.TextField(default='Ingrese un breve resumen')),
                ('email', models.EmailField(max_length=60)),
                ('estado_civil', models.CharField(max_length=10)),
                ('direccion_calle', models.CharField(max_length=20)),
                ('direccion_numero', models.IntegerField()),
                ('es_representante', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion.usuario')),
                ('genero', models.ManyToManyField(help_text='Seleccione Genero/Sexo', to='gestion.Genero')),
                ('id_fk_Asamblea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.asamblea')),
                ('id_fk_comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.comuna')),
                ('id_fk_rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.rol')),
            ],
            options={
                'ordering': ['usuario', 'fecha_modificacion', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AprobacionPA',
            fields=[
                ('tipo', models.CharField(default='aprueba o rechaza', max_length=50)),
                ('comentario', models.TextField(default='Ingrese un breve comentario')),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion.usuario')),
                ('id_fk_propuesta_asamblea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.propuestaasamblea')),
            ],
            options={
                'ordering': ['tipo', 'fecha_modificacion', 'fecha_creacion'],
            },
        ),
    ]
