# Generated by Django 3.1.7 on 2021-03-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='nombre_genero',
            new_name='name',
        ),
    ]
