# Generated by Django 3.1.7 on 2021-03-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20210313_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprobacionpa',
            old_name='id_fk_propuesta_asamblea',
            new_name='propuesta_asamblea',
        ),
        migrations.RenameField(
            model_name='estadocivil',
            old_name='name',
            new_name='nameEC',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='name',
            new_name='nameGE',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='id_fk_Asamblea',
            new_name='asamblea',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='id_fk_comuna',
            new_name='comuna',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='id_fk_rol',
            new_name='rol',
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='id_fk_tema',
            new_name='Tema',
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='id_fk_propuesta_asamblea',
            new_name='propuesta_asamblea',
        ),
    ]
