# Generated by Django 3.1.7 on 2021-03-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20210313_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='id_fk_distrito',
            new_name='distrito',
        ),
    ]
